name: CI

on: [pull_requests]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run a multi-line script
      run: |
        echo $GITHUB_EVENT_NAME	
        echo $GITHUB_ACTION
        echo $GITHUB_SHA
        echo $GITHUB_REF
        echo $GITHUB_HEAD_REF
        echo $GITHUB_BASE_REF
